# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestaddmypets():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testaddmypets(self):
        self.driver.get("https://petfriends.skillfactory.ru/")
        self.driver.set_window_size(1550, 878)
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.LINK_TEXT, "У меня уже есть аккаунт").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "pass").send_keys("12345")
        self.driver.find_element(By.ID, "email").send_keys("stvol@yandex.ru")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.LINK_TEXT, "Мои питомцы").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-success").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("koti")
        self.driver.find_element(By.ID, "animal_type").click()
        self.driver.find_element(By.ID, "animal_type").send_keys("dvor")
        self.driver.find_element(By.ID, "age").click()
        self.driver.find_element(By.ID, "age").send_keys("4")
        #self.driver.find_element(By.ID, "pet_photo").click()
        #self.driver.find_element(By.ID, "photo").send_keys("images\cat2.jpeg")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
        #self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) div").click()
        #self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
        self.driver.close()
