# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTestregistrashen:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testregistrashen(self):
        self.driver.get("https://petfriends.skillfactory.ru/")
        self.driver.set_window_size(1550, 878)
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("kol567")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("kol@yandex.ru")
        self.driver.find_element(By.ID, "pass").click()
        self.driver.find_element(By.ID, "pass").send_keys("12345")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.close()
