# -*- coding: utf-8 -*-
# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By



class TestTestaddmygrup():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testaddmygrup(self):
        # open nome page (отк. сайта)
        self.driver.get("https://petfriends.skillfactory.ru/")
        # size open windows (размеры отк окна)
        self.driver.set_window_size(1550, 878)
        # click
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.LINK_TEXT, "У меня уже есть аккаунт").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "pass").send_keys("12345")
        self.driver.find_element(By.ID, "email").send_keys("stvol@yandex.ru")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.LINK_TEXT, "Мои питомцы").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-secondary").click()
        self.driver.close()
